spring:
  datasource:
    username: root
    password: migi987
    url: jdbc:mysql://localhost/student_course_schema?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      use_sql_comments: true
      format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

